---
swagger: "2.0"
info:
  description: "保険商品情報の登録、照会、更新、削除のためのAPIです。"
  version: "1.0.0"
  title: "保険商品情報(Open API Specifications 2.0)"
# host: "api.jp.oraclecloud.com"
# basePath: "/insurance"
schemes:
- "https"
produces:
- "application/json"
paths:
  /product:
    get:
      tags:
      - "Products"
      summary: "保険商品情報の取得"
      description: "保険商品をカテゴリ、名前で検索します。"
      operationId: "productsGET"
      parameters:
      - name: "api-key"
        in: "header"
        description: "API Key"
        required: true
        type: "string"
      - name: "c"
        in: "query"
        description: "商品カテゴリ"
        required: false
        type: "string"
      - name: "p"
        in: "query"
        description: "商品名"
        required: false
        type: "string"
      - name: "pid"
        in: "query"
        description: "商品ID"
        required: false
        type: "string"
      responses:
        200:
          description: "保険商品情報"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Product"
        404:
          description: "エラー（該当商品がない）"
          schema:
            $ref: "#/definitions/ErrorInfo"
      x-swagger-router-controller: "Product"
    post:
      tags:
      - "Products"
      summary: "保険商品情報の追加"
      description: "保険商品を追加します。"
      operationId: "productsPOST"
      parameters:
      - name: "api-key"
        in: "header"
        description: "API Key"
        required: true
        type: "string"
      - name: "newProduct"
        in: "body"
        required: true
        description: "追加したい保険商品情報"
        schema:
          $ref: "#/definitions/BaseInfo"
      responses:
        201:
          description: "保険商品情報"
          schema:
            $ref: "#/definitions/Product"
        403:
          description: "エラー（商品追加に失敗）"
          schema:
            $ref: "#/definitions/ErrorInfo"
      x-swagger-router-controller: "Product"
  /product/{pid}:
    put:
      tags:
      - "Products"
      summary: "保険商品情報の変更"
      description: "保険商品を変更します。"
      operationId: "productsPUT"
      parameters:
      - name: "api-key"
        in: "header"
        description: "API Key"
        required: true
        type: "string"
      - name: "pid"
        in: "path"
        description: "変更したい商品の商品ID"
        required: true
        type: "string"
      - name: "product"
        in: "body"
        required: true
        description: "変更したい保険商品情報"
        schema:
          $ref: "#/definitions/BaseInfo"
      responses:
        200:
          description: "保険商品情報"
          schema:
            $ref: "#/definitions/Product"
        404:
          description: "エラー（該当する商品がない）"
          schema:
            $ref: "#/definitions/ErrorInfo"
      x-swagger-router-controller: "Product"
    delete:
      tags:
      - "Products"
      summary: "保険商品情報の削除"
      description: |
        売り止めの保険商品を廃止します。
        
        activeフィールドがfalseに変わります。
        
        廃止日時にタイムスタンプが入ります（物理削除ではありません）。
      operationId: "productsDELETE"
      parameters:
      - name: "api-key"
        in: "header"
        description: "API Key"
        required: true
        type: "string"
      - name: "pid"
        in: "path"
        description: "変更したい商品の商品ID"
        required: true
        type: "string"
      responses:
        200:
          description: "保険商品情報"
          schema:
            $ref: "#/definitions/Product"
        403:
          description: "エラー（削除に失敗）"
          schema:
            $ref: "#/definitions/ErrorInfo"
        404:
          description: "エラー（該当する商品がない）"
          schema:
            $ref: "#/definitions/ErrorInfo"
      x-swagger-router-controller: "Product"
definitions:
  Product:
    type: "object"
    properties:
      pid:
        type: "string"
        description: "商品ID"
      base_info:
        $ref: "#/definitions/BaseInfo"
      active:
        type: "boolean"
        description: "アクティブ・非アクティブ"
      created_at:
        type: "string"
        description: "作成日時"
      updated_at:
        type: "string"
        description: "最終更新日時"
      retired_at:
        type: "string"
        description: "廃止日時"
  BaseInfo:
    type: "object"
    properties:
      category:
        type: "string"
        description: "商品カテゴリ"
      product_name:
        type: "string"
        description: "保険商品の基本情報"
      overview:
        type: "string"
        description: "商品の概要"
      url:
        type: "string"
        description: "商品情報を掲載しているURL"
  ErrorInfo:
    type: "object"
    properties:
      code:
        type: "string"
        description: "エラーコード"
      message:
        type: "string"
        description: "エラーメッセージ"
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /InsuranceProduct/1.0.0