FORMAT: 1A
HOST: http://apics.oracle.com:7201/

# ホテル検索・予約

都市名や地域、宿泊日時などをもとに、ホテルの空室検索・予約するためのAPIです。

利用にあたっては、API Keyが必要です。

## ホテルを探す [/hotels{?country,pref,city,detail,name,in,out,adult,child,roomCnt,min,max}]

### Search [GET]

地域、都道府県などで検索します。
国コード、都道府県コード、市区町村コードは必須です。
空室がない部屋仕様やホテルは検索結果に現れません。

+ Parameters

    + country : `JP` (string, required) - 国コード
    + pref : `13` (string, required) - 都道府県コード
    + city : `13103` (string, required) - 市区町村コード
    + detail : `Aoyama` (string) - 地域コード
    + name : `オラクルホテル青山` (string) - ホテル名
    + in : `2017-02-10` (string) - チェックイン日
    + out : `2017-02-13` (string) - チェックアウト日
    + adult : 2 (number) - 大人の人数
    + child : 2 (number) - 子供の人数
    + min : 10000 (number) - 金額の下限
    + max : 50000 (number) - 金額の上限

+ Request (application/json)

    + Headers

            api-key : 6d1a4960-29a4-43d2-9ae5-670ed0b0b57f

+ Response 200 (application/json)

    + Attributes(TResult)

+ Response 404 (application/json)

    + Attributes(TError)

## 宿泊を予約する [/hotels]

### Booking [POST]

ホテルの部屋を予約します。
ホテルID、部屋の種類、人数、チェックイン、チェックアウト日が必須です。
予約が完了すると、レスポンスとして予約IDが戻ります。

+ Request (application/json)

    + Headers

            api-key : 6d1a4960-29a4-43d2-9ae5-670ed0b0b57f

    + Attributes(TBookRequest)

+ Response 201 (application/json)

    + Attributes(TBookResponse)

+ Response 403 (application/json)

    + Attributes
    
        + code: E002 (string) - エラーコード
        + info: ○●の理由で予約できませんでした (string) - エラーの詳細

+ Response 404 (application/json)

    + Attributes
    
        + code: E001 (string) - エラーコード
        + info: 予約可能な部屋がありません (string) - エラーの詳細

## Data Structures

### TResult
+ totalPage: 10 (number) - 検索結果の全ページ数
+ currentPage: 1 (number) - 現在のページ
+ contents: (array[THotel]) - 検索結果

### THotel
+ hotelId: H0001 (string) - ホテルID
+ name: オラクルホテル青山 (string) - ホテル名称
+ url: `http://www.oracle.com/jp` (string) - ホテルのURL
+ address: 東京都港区青山2-5-8 (string) - ホテルの所在地
+ comment: 新しい、清潔なホテルです。 (string) - ホテルのアピールコメント
+ in: `15:00` (string) - チェックイン開始時刻
+ out: `12:00` (string) - チェックアウト時刻
+ rooms: (array[TRoom]) - 利用可能な部屋

### TRoom
+ roomId: F001 (string) - ルームID
+ name: ファミリー (string) - 部屋名、仕様名
+ smokable : false (boolean) - 喫煙可、不可
+ charge: 12000 (number) - 宿泊代金
+ unit:  JPY (string) - 通貨単位
+ info: ツインベッド、40m2のお部屋です。 (string) - 部屋を説明する情報

### TError
+ code: E001 (string) - エラーコード
+ info: エラーメッセージ (string) - エラーの詳細

### TBookRequest
+ hotelId: H0001 (string) - ホテルID
+ inDateTime: `2015-08-27T21:33:20Z` (string) - チェックイン日時
+ outDatetime: `2015-08-27T21:33:20Z` (string) - チェックアウト日時
+ roomId: F001 (string) - ルームID
+ NumOfAdult: 2 (number) - 大人の宿泊人数
+ NumOChild: 2 (number) - 子供の宿泊人数
+ tx_id 94879 (string) - 取引トランザクションID

### TBookResponse
+ bookingId: H0001 (string) - ホテルID
+ tx_id 94879 (string) - 取引トランザクションID