FORMAT: 1A
HOST: https://gw-api.us2.oraclecloud.com/Energy

# 光熱費・消費量

お客様番号を使って、今日現在の今月分の光熱費と消費量、および先月の光熱費と消費量を取得できます。

API KeyとTenant IDをHeaderに設定する必要があります。

### 今月分 [/usage/current/month/{_id}]

### 今日現在の今月の光熱費と消費量 [GET]

+ Parameters

    + _id : `4859634` (string) - お客様番号

+ Request 

    + Headers
    
            tenant_id : 1
            api-key : 6d1a4960-29a4-43d2-9ae5-670ed0b0b57f

+ Response 200 (application/json)

    + Attributes(ConsumptionInfo)

### 先月分 [/usage/last/month/{_id}]

### 先月分の光熱費と消費量 [GET]

+ Parameters

    + _id : `4859634` (string) - お客様番号

+ Request 

    + Headers
    
            tenant_id : 1
            api-key : 6d1a4960-29a4-43d2-9ae5-670ed0b0b57f

+ Response 200 (application/json)

    + Attributes(ConsumptionInfo)

## Data Structures

### ConsumptionInfo
+ account_number: `4859634` (string) - お客様番号
+ name: Darko (string) - 顧客名
+ gas_usage: `20,006 Btu` (string) - ガス使用量
+ gas_cost: `¥ 46,896` (string) - ガス料金
+ electricity_usage: `3,430 kW` (string) - 電力使用量
+ electricity_cost: `¥ 12,932` (string) - 電気料金
+ enviornment: `Japan 1` (string) - 環境