FORMAT: 1A
HOST: https://gw-api.jp.oraclecloud.com

# 保険商品情報

保険商品情報の登録、照会、削除のためのAPIです。

利用にあたっては、API Keyが必要です。

## 保険商品情報 [/insurance/product{?c,p,pid}]

### 検索・取得 [GET]

保険商品をカテゴリ、名前で検索します。

+ Parameters

    + c : `AUTO` (string) - 保険商品カテゴリ
    + p : `○●総合自動車保険` (string) - 保険商品名
    + pid : `AUTO-201` (string) - 商品ID

+ Request 

    + Headers

            api-key : 6d1a4960-29a4-43d2-9ae5-670ed0b0b57f


+ Response 200 (application/json)

    + Attributes

        + products : (array[Product]) - 保険商品情報

+ Response 404 (application/json)

    + Attributes(ErrorInfo)

### 追加 [POST]

保険商品を追加します。

+ Request (application/json)

    + Headers

            api-key : 6d1a4960-29a4-43d2-9ae5-670ed0b0b57f

    + Attributes(BaseInfo)

+ Response 201 (application/json)

    + Attributes(Product4Create)

+ Response 403 (application/json)

    + Attributes(ErrorInfo)


## 保険商品情報の変更・削除 [/insurance/product/{pid}]


### 変更 [PUT]

保険商品情報を変更します。

+ Parameters

    + pid: `AUTO-201` (required, string) - 商品ID

+ Request (application/json)

    + Headers

            api-key : 6d1a4960-29a4-43d2-9ae5-670ed0b0b57f

    + Attributes(BaseInfo)

+ Response 200 (application/json)

    + Headers

            api-key : 6d1a4960-29a4-43d2-9ae5-670ed0b0b57f

    + Attributes(Product)

+ Response 404 (application/json)

    + Attributes(ErrorInfo)

### 削除（廃止） [DELETE]

売り止めの保険商品を廃止します。

activeフィールドがfalseに変わります。

廃止日時にタイムスタンプが入ります（物理削除ではありません）。

+ Parameters

    + pid: `AUTO-201` (required, string) - 商品ID

+ Request (application/json)

    + Headers

            api-key : 6d1a4960-29a4-43d2-9ae5-670ed0b0b57f


+ Response 200 (application/json)

    + Attributes(Product4Delete)

+ Response 403 (application/json)

    + Attributes(ErrorInfo)
    
+ Response 404 (application/json)

    + Attributes(ErrorInfo)


## Data Structures

### BaseInfo
+ category: AUTO (enum, required) - 保険のカテゴリ
    + AUTO (string) - 自動車
    + EARTHQUAKE (string) - 地震
    + MARINE (string) - 船舶
+ product_name: ○●総合自動車保険 (string) - 商品名称
+ overview: 自家用車むけの総合保険です。 (string) - 商品の概要
+ url: http://xxx.yyy.zz/AUTO-201 (string) - 商品情報を掲載しているURL

### Product4Create
+ pid: `AUTO-201` (string, required) - 商品ID
+ base_info: (BaseInfo, required) - 保険商品の基本情報
+ active : true (boolean, required) - アクティブ・非アクティブ
+ created_at : `2010-04-01T00:00:00Z` (string)  - 作成日時
+ updated_at : `2015-03-31T23:59:59Z` (string)  - 最終更新日時
+ retired_at :  (string)  - 廃止日時（作成時には設定されていない）

### Product
+ pid: `AUTO-201` (string, required) - 商品ID
+ base_info: (BaseInfo, required) - 保険商品の基本情報
+ active : true (boolean, required) - アクティブ・非アクティブ
+ created_at : `2010-04-01T00:00:00Z` (string)  - 作成日時
+ updated_at : `2015-03-31T23:59:59Z` (string)  - 最終更新日時
+ retired_at : `2015-03-31T23:59:59Z` (string)  - 廃止日時

### Product4Delete
+ pid: `AUTO-201` (string, required) - 商品ID
+ base_info: (BaseInfo, required) - 保険商品の基本情報
+ active : false (boolean, required) - アクティブ・非アクティブ
+ created_at : `2010-04-01T00:00:00Z` (string)  - 作成日時
+ updated_at : `2015-03-31T23:59:59Z` (string)  - 最終更新日時
+ retired_at : `2015-03-31T23:59:59Z` (string)  - 廃止日時

### ErrorInfo
+ message : エラーメッセージ (string) - エラーメッセージ