/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime

case class BaseInfo (
  /* 商品カテゴリ */
  category: Option[String],
  /* 保険商品の基本情報 */
  productName: Option[String],
  /* 商品の概要 */
  overview: Option[String],
  /* 商品情報を掲載しているURL */
  url: Option[String]
) extends ApiModel


