/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime

case class Product (
  /* 商品ID */
  pid: Option[String],
  baseInfo: Option[BaseInfo],
  /* アクティブ・非アクティブ */
  active: Option[Boolean],
  /* 作成日時 */
  createdAt: Option[String],
  /* 最終更新日時 */
  updatedAt: Option[String],
  /* 廃止日時 */
  retiredAt: Option[String]
) extends ApiModel


