FORMAT: 1A
HOST: https://129.150.81.75

# 空港情報（国内）

IATAコードを使って空港情報を検索します。
コード指定しない場合、国内の空港情報を全件取得できます。

## 国内の空港情報を取得する [/airports]

### 全件取得 [GET]

日本国内の空港情報を全件取得します。

+ Response 200 (application/json)

    + Attributes(Tairports)

    + Body

            {
                "airport": [
                    {
                        "code": "CTS",
                        "name": {
                            "ja": "札幌(千歳)",
                            "en": "Sapporo (Chitose)"
                        }
                    },
                    {
                        "code": "SDJ",
                        "name": {
                            "ja": "仙台",
                            "en": "Sendai"
                        }
                    },
                    {
                        "code": "HND",
                        "name": {
                            "ja": "東京(羽田)",
                            "en": "Tokyo (Haneda)"
                        }
                    },
                    {
                        "code": "NRT",
                        "name": {
                            "ja": "東京(成田)",
                            "en": "Tokyo (Narita)"
                        }
                    },
                    {
                        "code": "NGO",
                        "name": {
                            "ja": "名古屋(中部)",
                            "en": "Nagoya (Chubu)"
                        }
                    },
                    {
                        "code": "*os",
                        "name": {
                            "ja": "大阪(すべて)",
                            "en": "Osaka (All)"
                        }
                    },
                    {
                        "code": "ITM",
                        "name": {
                            "ja": "大阪(伊丹)",
                            "en": "Osaka (Itami)"
                        }
                    },
                    {
                        "code": "KIX",
                        "name": {
                            "ja": "大阪(関西)",
                            "en": "Osaka (Kansai)"
                        }
                    },
                    {
                        "code": "UKB",
                        "name": {
                            "ja": "大阪(神戸)",
                            "en": "Osaka (Kobe)"
                        }
                    },
                    {
                        "code": "HIJ",
                        "name": {
                            "ja": "広島",
                            "en": "Hiroshima"
                        }
                    },
                    {
                        "code": "TAK",
                        "name": {
                            "ja": "高松",
                            "en": "Takamatsu"
                        }
                    },
                    {
                        "code": "FUK",
                        "name": {
                            "ja": "福岡",
                            "en": "Fukuoka"
                        }
                    },
                    {
                        "code": "KKJ",
                        "name": {
                            "ja": "北九州",
                            "en": "Kitakyushu"
                        }
                    },
                    {
                        "code": "NGS",
                        "name": {
                            "ja": "長崎",
                            "en": "Nagasaki"
                        }
                    },
                    {
                        "code": "KOJ",
                        "name": {
                            "ja": "鹿児島",
                            "en": "Kagoshima"
                        }
                    },
                    {
                        "code": "OKA",
                        "name": {
                            "ja": "沖縄(那覇)",
                            "en": "Okinawa (Naha)"
                        }
                    }
                ]
            }

## 3レターコードで検索する [/airports/{code}]

### 検索 [GET]

3レターコードを使って国内の空港情報を取得します。
3レターコードを使わずに呼び出すと、日本国内の空港情報を全件取得できます。

+ Parameters

    + code : `HND` (string) - 空港コード(3レター)

+ Response 200 (application/json)

    + Attributes(Tairports)

    + Body

            {
                "airport": [
                    {
                        "code": "HND",
                        "name": {
                            "ja": "東京(羽田)",
                            "en": "Tokyo (Haneda)"
                        }
                    }
                ]
            }
        
## Data Structures

### Tairports
+ airport: ``(array[Tairport]) - 検索結果

### Tairport
+ code: `HND` (string) - 3レターコード
+ ja: `東京(羽田)` (string) - 空港名称（日本語）
+ en: `Tokyo (Haneda)` (string) - 空港名称（英語）